const attemptData = ['Ninth', 'Tenth', 'Thirteenth', 'Eleventh', 'Twelth' ,
'Not sure if this fits the sub, but it is funny.', 'What?' ,
'Elephants are great',
 'There was a success',
 'Oh my god take your well deserved karma �' ,
'And that’s why you cut off the top and bottom first',
 'The number of pieces this melon exploded into almost perfectly resembles the number of times this gif has been posted in this subreddit before. \n\n\nNature is truly amazing.',
 'You have to cut the top first, don\'t? Like cutting a pineapple',
 'Bitch I see u tryna cut fruit like sum god damn samurai wit a broken sword dat ain’t goin work lemme show u how to samurai this BITCH',
 'I\'ve seen this so many times and I still enjoy it. Absolutely gorgeous!',
 'r/mildyinfuriating',
 'S̸̢̧̧̛̬̠̩̞̗̼̞̺̺̲̠͆ͅQ̶̧̨̩̗̹͕̞̠̰̹̫̠́̊̀̋̑̒̇̚͠U̸͇̟̳̱̻̩̖̲̳̤͚͎̥̭͂͋̌͗͋̀̆̿̈́̈͋̉̈͝Į̶̟̫̿͌̓̔̔̿̌͗̓͘S̴̡̧͈̠̥̣̭̻̩̩̱͖͍̘̀͆̇͆̔̆H̷̛̟̞͙̟̦̞͛̋̓̈́͂̾̚͜' ,
'To be fair, there are many situations where having an agreed-upon common language is much more inclusive and respectful than having small groups of people who do not communicate with each other. You cannot "connect cultures" if no one is speaking the same language.',
 'Looks edited.',
 'If you haven\'t noticed the uk is in the middle of the world, thats why',
 'Waarom?' ,
'No sandwich making on drugs.' ,
'It was a long walk back to the break room for Jeorgie',
 'You fool!',
 'That\'s me in rainbow six siege ���' ,
'r/instantkarma',
 'r/justiceserved',
 'A major oof moment',
 'Bitches be crazy.',
 'therewasanattempt 1 month ago(https://www.reddit.com/r/therewasanattempt/comments/cipftk/to_throw_acid_in_her_exs_face/)\n\ntherewasanattempt 1 month ago(https://www.reddit.com/r/therewasanattempt/comments/cirzas/to_throw_acid_on_exs_face/)\n\ninstantkarma 1 month ago(https://www.reddit.com/r/instantkarma/comments/cimg79/woman_tried_to_acid_attack_her_former_lover/)\n\ninstantkarma 1 month ago(https://www.reddit.com/r/instantkarma/comments/cimg79/woman_tried_to_acid_attack_her_former_lover/)\n\ndankmemes 1 month ago(https://www.reddit.com/r/dankmemes/comments/ciu47q/big_oof/)\n\nMGTOW 1 month ago(https://www.reddit.com/r/MGTOW/comments/ciqapn/thats_the_way_the_wind_blows/)\n\nWhatcouldgowrong 1 month ago(https://www.reddit.com/r/Whatcouldgowrong/comments/civ9it/wcgw_if_i_throw_acid/)' ,
'This is why pugs have smushy faces.',
 'That went from doggo to loggo really quickly.',
 'Pounding some wood, there, doggo?',
 '“Oof, Oh ow, god ow, stop filming.”',
 '"I got it, I GOT IT!!"',
 'This. Is. Me. Every. Single. Day.',
 'Story of my life so far...',
 'The spirit of Loca lives on(https://www.youtube.com/watch?v=x2RJN9a_jdM)',
 'As a pug owner, can confirm that they run head first into things all the time.',
 'Tuck and roll big guy. Nice attempt :)' ,
'So professional. So good. So adult.',
 'Uno is the exact opposite of the UN!',
 'Also used the word \'ur\'' ,
'Why would you even photoshop the sky? Presumably it\'s already there in the picture of the place you want to pretend you\'ve been to, no?',
 'Don’t let those cloud your judgement of the importance of her influence',
 'Those are some nice clouds, not gonna lie',
 'She\'s an "influencer" so what didya expect?',
 'All her followers are in the cloud.',
 'The clouds decide where she visits next',
 'r/instagramreality',
 'There was an article on this, she’s always been open about the use of photoshop on her pictures',
 'She literally has everything pre and post photoshop pics on her account stories . Just checked them when this same pic was posted in r/quityourbullshit.',
 '"There was an attempt" well she successfully attempted the photoshop. Perhaps title could be worked on',
 'I\'m so sick of these influencer people. Get a job god dammit.',
 'I guess its the feeling that matters am i right lads or am i right lads??? ... ? ..ok',
 '/r/instagramreality',
 'Xiaomi camera app does this',
 'She could have literally rotated and flipped some clouds to help avoid being caught. It takes two seconds. Sloppy.' ,
'Genuis idea',
 'This is genius! I wonder how long it\'ll keep the pup entertained? Either way it\'s good exercise for him lol',
 'this reminds me of the joke in elementary school where you would write "How do you keep an idiot busy?  Read the other side to find out." on both sides of a piece of paper.',
 'in 12 years the rope will cut the tree down',
 'Brilliant',
 'Outstanding move',
 'Who ever set this is evil' ,
'How could she not assert domanince? Great, now the cat probably thinks he owns the place',
 'Don’t bring none, won’t be none.',
 'It cracks me up how the cat just starts bopping her towards the end',
 'Take that Spartan t-shirt off this instant! You are not worthy. ^The ^shorts ^too.',
 'Dominance asserted.' ,
'*stays crunchy, even in milk*',
 '“Prefer” so they could be convinced maybe?',
 'I wonder, is cannibalism vegan?',
 'He didn\'t say we couldn\'t eat them. They would rather we don\'t eat animals either but num num num.',
 'And who’s stopping me, you grass-fed fuckholes' ,
'Lazarbeam can demonetize everyone',
 'Love how he contines to curse even after they say dont',
 'Aww shit! That\'s hilarious',
 'What a bloody legend',
 'Thats lazar for ya' ,
'Attempt succesful. Escape unsuccesful.',
 'Sounds like his face said hello to the floor!',
 'Headbutt: The unmistakable move of somebody who has no fighting experience whatsoever, or a shit ton of it. He doesn’t look like a shit ton. Just like shit.',
 'a fight video with no staph? i cant believe it.',
 'You\'re fuckin\' done' ,
'*to stop in the middle of a crosswalk and not get punched',
 'Street fighter II',
 'r/GTAorRussia?',
 'Also r/semiinstantkarma' ,
'I think he meant to do that, otherwise why were they filming.......',
 'idk...kinda seems like he was intending doing that. And its really cool tbh',
 'He forgot he had it enchanted with Loyalty III r/minecraft',
 'That\'s so cool',
 'Plant parachute',
 'The new Thor movie looks cool',
 'Tf is that you thor',
 'So that\'s how Mary Poppins did that.',
 'Prehistoric frisbee!',
 'Thors hammer in disguise',
 'he’s still worthy',
 'If you love something set it free. If it comes back, it’s yours.',
 'Ladies and gentlemen, It is him Thor! (this time he used groot\'s limb)',
 'Look, I\'m a jerk that rips up bushes.',
 'this must be the tree that grew from Donny’s ashes',
 'Great, one more thing all these influence idiots are going to copy for hits.',
 'If you love it let it go, but if it comes back it\'s meant to be',
 '*What kind of black magic is this?*',
 'Wingardium leviosa. Not leviosá!',
 'Task Failed Successfully.' ,
'Did the guy in the TRUCK get out before it BLEW UP?',
 'On top of everything else hes going to have to reset his \'days since I caught fire\' counter at work.',
 'i thought chinese people were evil and callous. they would never help someone in an accident. what happened? why did they run next to a raging fire to pull some guy away???',
 'The ammunition has detonated',
 'How to drive 101 ^^^',
 'Lol the guy that pours his drink on him',
 'LOL some people just deserve the shit they get' ,
'r/ConvenientCop',
 'this was so satisfying to watch',
 'Good ole Medicine Hat',
 'How does he know it’s stolen? Does the card reader say something other than declined?\n\n*EDIT:* I did some research on this because I was really curious and it\'s somewhat related to my work. According to page 38 of the Visa card acceptance guidelines(https://usa.visa.com/dam/VCOM/download/merchants/card-acceptance-guidelines-for-merchants.pdf) one of the responses can be "Pick Up".\n\n***\n\n|Response|Meaning|\n|:-|:-|\n|Approved|Card issuer approves the transaction. This is the most common response.|\n|Declined or Card Not Accepted|Card issuer does not approve the transaction. The transaction should not be completed. Return the card and instruct the cardholder to call the card issuer for more information on the status of the account.|\n|Call, Call Center, or Referrals|Card issuer needs more information before approving the sale. You should call your authorization center and follow whatever instructions you are given. In most cases, an authorization Agent will ask to speak directly with the cardholder or will instruct you to check the cardholder’s identification.|\n|**Pick Up**|**Card issuer wants to recover the card. Do not complete the transaction. Inform the customer that you have been instructed to keep the card, and ask for an alternative form of payment. If you feel uncomfortable, simply return the card to the cardholder.**|\n\n&amp;#x200B;\n\n# Recovered Cards\n\nIn general, you should recover a card if you have reasonable grounds for believing the card is being used fraudulently or is altered or counterfeit and it can be done safely. The following situations are considered reasonable grounds for recovery:\n\n* Card security features are missing or irregular, or appear to have been tampered with (See Visa Card Features and Security Elements on page 26 of this document.)\n* The account number on the magnetic-stripe does not match the number embossed on the front of the card (See Doing It Right at the Point of Sale on pages 20 through 25 of this document.)\n* You receive a pick-up response when a card has been swiped for electronic authorization.\n\n## Card Recovery Procedures\n\nThe following card recovery procedures apply to all Visa credit, debit, prepaid and Visa Electron cards:\n\n* Recover the card only if you can do so safely. Never take unnecessary risks.\n* Tell the cardholder you have been instructed to keep the card, and that he or she may call the card issuer for more information.\n* Remain calm and courteous. If the cardholder behaves in a threatening manner, return the card immediately.\n* Make a readable copy of the front and back of the card, if possible.\n* If the recovered card is retained by law enforcement officials, you must give your acquirer a readable copy to be eligible for a reward.\n* Cut the card according to acquirer procedures.\n* Tell your acquirer that you have recovered a card and ask for further instructions.\n\nFor cards that are inadvertently left at a merchant location and remain unclaimed, follow the procedures for contacting your acquirer and sending in the card.\n\n***\n\nAlso, fuck that. I\'m not holding that card in any situation, 100% not my job. Say it\'s declined and let the system figure it out. Obviously the card can\'t be used anymore and they have a record of where it\'s been.',
 'Haha does the cop drop some change on the counter before leaving? I think he paid for a coffee or something mid-arrest.',
 'Talk about having your job gift wrapped...',
 'Officer just grinning away watching it all unfold in front of him.',
 'Background song to watch it(https://www.youtube.com/watch?v=6MYAGyZlBY0)',
 'Lol how cocky. he even opened the drink before paying for it.' ,
'"I\'m just gonna pretend I was looking for a comfy spot to lie down"',
 'Sneak 0',
 'They get so embarrassed when they fall or fail. They start doing cat things like what this one does or they start rapidly licking themselves',
 'Me when i try to get my life together',
 'He just accepted his fate'
]
const metaCanadaData =  [
  'Wonder if there was any Unifor poison pill to make Unifor union raiding in the media sector easier, just like the dirt deal Unifor got from the Ontario Wynne Liberal.\n\nNo, I don\'t have access to the full article, nor an alternative source given it is likely original reporting from ATI requests by this outlet, you can pay them to view or you can wait until another outlet gets a hold of the record, if ever.' ,
    'Would be funny if they weren\'t driving a country into the ground...' ,
    'Negative eleven months?\n\nhttps://globalnews.ca/news/4558996/cannabis-pardons-simple-possession/',
     'Betting; That he waiting till the election is on to announce it because Marijuana effects your short term memory.\n\nAsk a Liberal about Trudeau promising voter reform or that 2015 was promised as the last "first past the post" election and they will stare in confusion.\n\nThey always "Remember things differently"' ,
    'No were good . The GTA is the best place to stay. Nothing fun or nice to see in the rest of the province. Little towns and bonded communities arent the place to raise your 15 children',
     'In other words, live elsewhere so we can get votes for a major leftist government.',
     'Ewwww no',
     'GTA is the best!  Multiculturalism at its finest!  Toronto will welcome you with open arms!' ,
    'This was from the run up to the UN compact signing in Dec of last year...Canada has since signed and therefore agreed to this...but shhh...no one\'s supposed to know.',
     'I wonder why there was such an outrage over those PPC billboards speaking out against migration?',
     'UN must be disbanded',
     'Governments make immigration policy.  It’s not possible to criminalize discussion of government policy in democracies.\n\nWho are those totalitarians?',
     'Boogaloo' ,
    '"Is that a city in Quebec?"',
     'Holy fuck, the dream. Although I say an independent republic free of America’s and eastern Canada’s bull shit is the way forward',
     'Accurate',
     'Guys don\'t tease me like this \n\nI don\'t even believe is god but this is the one prayer I send up just in case.',
     'He knows that it\'s the place where they make him wear a hat.',
     'Fuck Alberta' ,
    'Coincidentally, the children still pay',
     'How many Reddit\'s can you cross post this to?',
     'That field of study is dominated by feminists.  \n\nThey likely decided the bodies were sacrifice victims because they ‘felt it in their vaginas’ (to quote the head of NOW).',
     'Nothing gets the liberal cucks riled up like bad weather (aka climate change).  They just love finding new ways to give money to the federal government to NOT stop bad weather from happening.' ,
    'There is no way in hell Alberta will ever go left after the disastrous NDP era they had.',
     'How can the Liberals be second?',
     'Has alberta ever voted anything but conservative?' ,
    'That’s just extremely sad and no amount of argument will convince me that this is not a terrible sin from whatever moral perspective you’d like to take',
     'Wow, that\'s like 10% of the population. Why not just use birth control or the morning after pill? How is abortion that common? It\'s sad.',
     'Imagine how much more of a nation we would be if the people who built it kept building it. \n\nThis is what subversion looks like.',    'Good! We spend more than enough on other people’s neglected unwanted children as it is.',
     'It just makes more room for inbred Africans',
     'Not nice',
     'Theory of evolution dictates that if we keep this up, rapists and sluts won\'t reproduce. Only 950 more years of this and it will be genetically coded that rape doesn\'t work. Sluts will still exist though.' ,
    'Correction:  China lent us $250 million dollars, and then we donated that $250 million back after agreeing to pay interest on it because something reasons.',
     'yet the donations from China to the Trudeau foundation has sky rocketed',
     'Sadly he\'ll probably win in October because the majority can\'t ween themselves from their lying TV\'s.',
     'This man is a walking disaster. EVERYTHING he does has maximum negative impact on Canada.\n\nAnd yet there are millions of dumbass Canadians who will vote for this freak in 2 months. A big Fuk You in advance to them.',
     'Why in the fucking hell are we giving any money to the worlds strongest economy?',
     '...while he successfully destroyed oil pipeline project in Alberta and used a billion from taxpayers money to do it.',
     'Can’t even replace the massy tunnel (dangerous and from the 60s) in metro Vancouver but can give 250m to China so they can WTF',
     'They don\'t need our god damn money!',
     'Born to Cuck.  Right Mr. Castreau?',
     'And all of that because China is a "Third World Country"',
     'How does the most populous country in the world need donations from other countries?',
     'A vassal does not stop paying tribute to their lord just because they don\'t agree with the lord\'s policies. That is, a loyal vassal does not.',
     'I\'ve NEVER hates anymore as much as I HATE this cuck',
     'Am i missing something? Why in gods name would Canada be giving money to China? Are we living in some kind of make believe world?',
     'So did we help build that bridge to Hong Kong. Any future blood will be on Trudeau\'s hands!',
     'But Little Potato thinks their release is imminent, due to his virtuosity. He\'s the kid on the playground, emptily sanctimonious that no one likes, but he has no concept.',
     'Yes he can, please don\'t challenge him',
     'What a limp dick for a leader' ,
    'Muh socioeconomic factors',
     'But its legal in Ethiopia and the white bitches are so much hotter says the vowel fook.' ,
    'Good on the PPC for improving their numbers lately.  \n\nThese polls will be a lot more interesting when September comes around.  I wonder how many people are being "silent" conservatives and saying they will vote for Liberals when in reality they are going to vote conservatives when the day comes.',
     'I\'m enjoying this trend. As a center lefty who has voted Liberal my entire life... I\'m god damn eager to see those fuckers... and Trudeau in particular kicked to the curb. Trudeau\'s sanctimonious, politically religious, Regressive Leftism has infected the entire party and I will never vote for them while it remains. Give me the Cons for now... and better yet... in time... anti globalist Bernier and PPC. Yes I\'m center left... but I love the West... and I\'ll stand as allies with any right leaning fellow citizens who will fight for the West. We may have some differences... but if we can agree that the Western world has achieved so much to be proud of, has made life better for so many people, and brought more freedom then ever before... I can get past the disagreements and have sane debate. \n\nBut the extremist nutcases need to be stopped and right now the Regressive Leftists are doing the most damage.',
     'Don\'t give me hope like that. Just don\'t :(',
     'Looks like milk is back on the menu boys!',
     'It\'s sad that with all that the Liberals are experiencing differently, Canadians aren\'t aware (really) of what\'s going on in Ottawa right now, and polling is reflecting that.\n\nI remember the very same media outlets that are like running the bare minimum coverage of SNC and Raybould, running non-stop wall-to-wall coverage of Duffy (which I will remind everyone was a party *paying back* expenses it felt one of its legislative members wasn\'t entitled to - tell me again how many Liberal scandals have ended with the treasury being made whole?) literally until he lost and they no longer needed a hammer to beat him with.',
     'Sad that the NDP polls above 0.1% but otherwise that is broadly good news.' ,
    'The EU is the Fourth Reich.\n\nMerkel has done more to destroy Europe than Hitler ever dreamed of doing.' ,
    'The Chinese have been doing this for decades.  \nThose of us who buy silver or gold, NEVER buy from China. 9 times out of 10 it will be less than 10% actual precious metal.   \nBut you will pay full price for it.' ,
    'Voting is now open......we haven\'t made up our minds yet because the alcohol has yet to run out.',
     'Finally. About time mods get off their asses and DO something around here.' ,
    'I\'ve started to notice things',
     'Sorry, *person*let',
     'Well he\'s an orange Tory so take it for what you will.',
     'Remember how the meme used to be: "Wrong Party Chong"?\n\nAre we still so sure about that?  What\'s the difference between Scheer and Chong at this point?  Not much in my opinion.  They\'re the same guy with the same brand of weak leadership and Jello for spines.  \n\nScheer / Chong = LibCon part 2.0  : /' ,
    'If this is where my money is going.... I think I’m gonna go donate some more. Lol',
     '"Say YES to reviewing my snow crab proposal"',
     'LOL...',
     '"I want to, ow you say, pipe May in the backyard, ya know?\n\nI pipe dat good."',
     'How long till some enterprising young man uses that app to smash Bernier and Mays faces on something from my second favourite webpage....' ,
    'There is enough of this stuff in country to kill almost everyone.\n\nWaiting for some jihadi to rent a plane and start dumping bags of it out over a city.',
     'Not just China. Those Islamists in Toronto had enough fentenyl to peacefully kill everyone in  ~~the GTA~~ Canada, and then some..\n\nWeaponised aerosol of peace.\n\nWhen the narcan wears off, you\'re dead.',
     'Chinese news, 1830-1860:\n\n"Opium is a weapon from Britain to mass murder our citizens"',
     'Take a drive around Alberta and look at the junkies roaming the streets of small towns. Pretty sad.',
     'I’ve long advocated for an all out military attack on China and Chinese outside of China.\n\nChina should have been destroyed decades ago when it would have been a trivial exercise, but it’s not too late to eliminate their existential threat to the west.',
     'Makes more sense if China didn\'t have the same problem.  They eradicated natural opium production and have a vast synthetic market to replace it, of course.  Folks want their druuugs.\n\nBut greed comes into play and only a minute amount of fentanyl cut  with bullshit is enough to get masses high, building profit margins for criminal enterprises.\n\nHowever, if you\'re into conspiracies, then the big one right now is that weaponized fentanyl is being put out there to kill more of the poor, period.  Considering the lowly drug addicts have no future anyway, they are often the first to be offed in population control efforts.  The result will be less burdens for the state and more productive people, and it has soft quite support from the majority of the public.  ie.  Nobody gives a shit when scumbag addicts die.',
     'Recreational fentanyl is the best thing to hit the street in my opinion. Let the crack heads who steal shit and are a constant drain on our society fucking die. No more naloxone kits.',
     'Fentanyl should be treated as a weapon of mass destruction when convicting traffickers.',
     'Sorry no. A weapon is used against someone, these people are voluntarily using a product someone else makes.' ,
    'Why do these shitty memes keep getting sticked?',
     'Toronto Star. My cat won\'t even have that shitrag for a liner in the litter box.',
     'Lol',
     'More like the Toronto Red Star.',
     'British-tier post mate  \nHope you got yer loisence' ,
    'You have been blocked by Hussen',
     'Sickening to see decent western people being replaced by the worst people on earth.  No country should have a Somali immigration minister.',
     'Has Max publicly called out the RCMP yet for not investigating Trudeau and his MP\'s on a charge of Obstructing Justice? \n\nIf so, I\'ll vote for him.',
     'Max, you shouldn\'t be running a fake party.' ,
    'But is it funny?',
     'Most based comic on Netflix you say?(https://youtu.be/2Tqw139rT30)',
     'Jokes?  In a netflix comedy special?  I thought the new comedy hotness was telling stories about the time you were raped and then preaching about feminism?\n\n Debbie Downer Sound(https://www.youtube.com/watch?v=ObdC3uhPeEY)',
     'He\'s not "based" he\'s just a normal person from the 80\'s / 90\'s  and he has "Fuck you" money so he can say what he actually thinks. Also he\'s black so white SJW\'s and other assorted communist dregs don\'t know how to attack him.',
     'A really solid special with some hard laughs. He represents HIS people though. Don\'t you think you should represent yours?',
     'Stolen material from Owen Benjamin',
     'Dave Chappelle? Isn\'t he a Liberian?',
     'I need to see the special.',
     'Awesome I will watch. Fuck pc shit. Fuck Hollywood bullshit.',
     'He literally said what every other comic has been saying in their acts and on their podcasts though. If you’re suddenly offended then you don’t follow comedy at all.',
     'Do not fall for Strangeteeth_\'s bullshit.\n\nJust a few things in the show Chapelle directly or indirectly said:\n\n1. Whites deserve opioid crisis and he likes it.\n\n2. Being molested is ok if famous people do it.\n\n3. Abortion is a woman\'s choice, men have no say.\n\n4. We need to disarm whites.\n\n5. LGBTQ ally!\n\nhttps://twitter.com/EvilHillaryPics/status/1166811895023755264',
     'The Michael Jackson bit is from south park in the early part of the but and he built more on it.\n\nThere are a few other bits like that.',
     'I\'m progressive and was not even close to offended.\n\nEdit: UH-OH that goes against the circle jerk in here!!!!!',
     'Baddest man alive to touch the mic' ,
    'Calling gay people together a marriage is like calling a dog\'s tail a leg.',
     'That awesome.' ,
    'If this is all about Liberal desperation, why is Scheer dancing to their tune?',
     'LOL Trudeau\'s refusing to participate in the debates? Holy shit.',
     'Thanks for coming out\\*, Andrew. You had this one chance\\*\\* to regain my vote and still don\'t have it. Mad Max ftw.\n\n\\*No pun intended\n\n\\*\\*Not strictly true as there\'s a few things he could say that would get my vote, but they would all be falsely labeled extremist so he won\'t' ,
    'The fucking cops have to run FUCKING TESTS to determine if they gun they found in the car is an airsoft or a real firearm! WHAT THE FLYING FUCK????',
     'Hey isn\'t that great!  They got a black reporter!  So diverse.  And isn\'t that what this is all about?  Totally worth it.\n\n/edit; and the diversity hire cop has to conduct "TESTS" to tell a real gun from an airsoft gun.',
     'LOL I think Coulter\'s law probably applies here.\n\nNo description, no race given, no names given... nothing.',
     'Youts',
     'Counter\'s law',
     'Gun Control narrative coming up. \n\nI have this feeling that this is the plan so that they can take away the guns,even if obtained lawfully. Could John Tory be behind this?',
     'Cops are being praised for doing a good job. Dude, if you have "teens" running around with guns you failed. You failed a long time ago. Meanwhile a law abiding citizen can\'t carry even rudimentary self-defense, while "teens" arm themselves to the teeth before being sent to criminal education center (prison) where they become more hardened criminals. What a joke.',
     '"names"?',
     'This couldn\'t be true.. why isn\'t it on r/toronto?',
     'With drool dripping from the corner of his mouth, John "D\'uh" Tory thinks this is the time, that simplistically trite stricter gun control will cure what ails us, because he so smart. And is clapping seal fan base goes ecstatic.',
     'ahhhhhh, kids will be kids these days, but they\'ll probably be dead before thy\'re men.',
     'Out on bail, or a "Promise"?'
     ]

const goingToHellData = [
  '"Mama, ooh\nI don\'t want to die\nI sometimes wish I\'d never been born at all..."',
    'No that\'s exactly *why* we are saying it.' ,
   'More like sunglasses for Irish girls dating muslims.' ,
   'alright alright alright' ,
   'More like China.\n\nThey already made bodies splatter along the floor with tanks.',
    'let the bodies hit the floor \nlet the bodies hit the floor \nlet the bodies hit the floor \nlet the bodies hit the ...',
    'Christopher Brown &amp; Robin Fentanyl' ,
   'nvm dude don’t mind my comment didn’t knew that everything that gets posted is flaired nsfw',
    'Reeee',
    'Long ago we lived by the facts, like for example the amazon experience far worse forest fires in the 90s and the 2000s.' ,
   'Reddit has gotten so lame. You get banned from everything for bullshit reasons. Power hungry mods',
    'I like your style',
    'Holy fuck thank you for making me laugh today',
    'tell them it was autocorrect from\n\nflying spaghetti monster',
    'Tfw r/askmen has women mods',
    'Askmen being led by feminists incels.' ,
   'LMAO!',
    'לא מצחיק- very funny!!!',
    'Wtf dude that’s terrible you’re going to hell for that',
    'Isn\'t Israel a country?',
    'Literally not a country : Pales what? What is that imaginary place?' ,
   'Bruh, putting Cosby and Harvey on the same level as Epstein is bonehead fucking retarded.',
    'What about Jackson and his apologist Dave "the statistical retard" Chapelle?' ,
   'Oh my gad, thos wyt pepl called me blak',
    'I bet fat brown bitch is a lesbian too',
    'They really reverse carded us',
    'I\'m glad so many are being so honest so early.\n\nPro tip: if you want to genocide a people,  *actually wait* to tell them until they are a minority. \n\nAt this rate, by 2080, America will be the strongest evidence  ever for "the only functional state is an ethnostate".' ,
   'Good dog', 'Lmao so funny xd', 'Cat?' ,
   'Poetry at its finest!' ,
   'Remember to change your gender fluid every 5,000 tweets or your social engine slows down.',
    'When your son being gay isn\'t special enough anymore so you cut his balls off and call him Susyn.',
    'And it seems the posts where you bring up the fact that you\'re bisexual for no apparent reason just haven\'t been getting the likes they used to...',
    'Are the initials Z and Q by chance?',
    'Who\'s the person in the background anyway',
    'Sounds like a shitty video game as well.',
    'DID YOU JUST ASSUME MY SPECIES',
    'Scariest thing on Reddit.',
    'This reminds of me the accusations Nathalie Laehead has made against Jeremy Soule. It\'s an epic attention grabbing cry fest from her.',
    'make an anti-trump tweet',
    'Isn’t CUTTING it. Nice pun.',
    'Why is this marked NSFW?' ,
   'I\'d be wiling to bet 90% of all fender benders and parallel parking accidents are women.',
    'Well he is technically a guy so..',
    'The same primal need to push the limits has literally landed man on the moon.' ,
  ,
   'Lord have mercy on my soul- said the priest after some light reading and heavy breathing',
    'from the Vatican Press...',
    'All profits from the sale of this magazine go to Cardinal George Pells legal defence in Australia.',
    'Oh for frock sakes',
    'I thought this was the Asian version for a second with the title of the mag.',
    'Not my proudest.',
    'I\'m still waiting for the issue where the Rabbi bites the baby boy\'s dick skin right off his genitals',
    'Wayyy less than I paid....',
    'The macualay culkin edition was their all time best seller',
    'LMAO' ,
   'Jamal visited Vietnam.',
    'Needs more jpeg',
    'Strange Fruit indeed...',
    'How do you get a black.man out of a tree in Mississippi? Cut the rope.',
    'https://youtu.be/Web007rzSOI',
    'Yeah, if they did I would still have one. Stupid Jamal.' ,
   'It being a billboard worthy issue is just....wow',
    'This is a fake billboard right? Please tell me this is fake',
    'Its ok, Allah is an excuse',
    'Getting is an drunk never excuse',
    'I\'m having a hard time figuring out what this billboard is trying to say. Are drunk people fucking their daughters?',
    'I hate this Alabama meme.\n\nIncest is severely punished there. Its New Jersey where its fully legal with people of proper consent age and in ohio where it is only parentaly restricted.\n\nSweet Home Ohio would be more fitting.',
    'https://www.tallahassee.com/story/news/2016/07/10/refuge-house-launches-campaign-combat-incest/86616974/',
    '*Florida',
    'I\'m from Alabama and this is hilarious.',
    'Oh, you can transgender but not fcuk your own grandma? How racist.',
    'Facts',
    'So is that inclusiveness working out for this billboard or is incest a minority thing?' ,
   '“Dude that’s what gave you the lice in the first place.”',
    'You weren\'t supposed to do that',
    'LMAO HAHAHAHAHAHAHAHAHAHAHAHA',
    'Whahah\n\nDear Sir,\n\nCould you provide me with a template for this beauty? \n\nYours Sincerely\n\nXnxx',
    'Wait, thats illegal',
    'Stupid' ,
   'For God’s sake. The Amazon burns every single year. Why is it a crisis now? This is not new!',
    'As a popeyes employee, Please kill me',
    'The Amazon burning is a controlled burn. It\'ll all regrow later. It\'ll help prevent wildfires in the future.' ,
   'Maybe that was the only one being stolen?',
    'Stereotypes don\'t lie',
    'Well, at least the prices are the same.',
    'Truth hurts a lot, blacks hurt everything' ,
   'Nigga just got his car stolen right from under his ass.',
    'Girl: Ok, so what\'s your hobby? We\'ll do that next!\n\nGuy: Um, uh, ok. So uh, you like bikes?',
    'Get Out 2',
    'Mermaid man and barnacle boy!  Who you calling boy, cracka?',
    'I want to smash the pot and look for arrows or rupees.',
    'The invisible boat mobile fit\'s on the porch?',
    'This nigga wearing white fucking cardboard behind his head so you can see his head...',
    ' TO THE INVISIBLE BOAT MOBILE!!',
    'Gross',
    'When did SpongeBob do an episode on date rape?',
    'I\'m sending this to all of my black friends. All 2 of then.',
    'removed',
    'Now I wanna smash the white girl too, that looks fun!\n\nShit, just outed myself . . .',
    'Squirtle and hurtle',
    'Eeeew a cellphone screenshot.',
    'Was going to say i have those shoes but they arent in my closet anymore',
    'At least the kid will have a pic of his dad',
    'Fucking white people.',
    'Haha, yes. Only black men would ever do stupid shit to get girls. White guys would never ever do anything silly to impress a chick.' ,
   'It\'s blatantly sexist for women to have different interests.',
    'Now someone just needs to insert a link to Jordan Peterson "equality of opportunity doesn\'t mean equality of outcome".',
    'Women always gotta ruin everything.'
]
const dankMemesData = [
  'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'They’re not in the trees, they *are* the trees',
    'Napalm sticks to babies.. crunchy on outside juicy on inside.',
    'The irony is killing me. Girls questioning why everyone just doesn\'t get along while girls are that one group seemingly never get along',
    'Run through the jungle intensifies',
    'I hope you make it to hot',
    'Wars are exciting. My favorite part of history',
    'r/okbubbyretard',
    'When the trees stary speaking Vietnamese',
    'almost laughed out loud in chem',
    'The real soldiers were the trees we met along the way',
    'We three trees from yonder glen',
    'Tôi là người việt và tôi xác minh việc này\n\nAhhhh nothing smell like a platoon dying in your bamboo trap in the morning',
    'Slow roasted goodness.',
    'Looks about right',
    'Make sure you sing "lemon tree" when your buddy is up on the trees',
    'These wimpy kid memes are restoring my will to live',
    '*clonk*',
    'pls make more memes with greg',
    'I am the lorax, I speak for the trees, the trees speak vietnamese',
    'Template',
    'I love these formats of Greg .. but why?',
    'Laugh in tree language.',
    'This is so sad,Alexa play fortunate son',
    'You just got Fragged',
    'Born to feel',
    'I hate these "boys vs girls" memes.' ,
   'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'It really do be like that',
    'squeak squeak squeak \nsqueak squeak squeak \nsqueak squeak squeak',
    'This is great meme',
    '49 times, we fought that beast...',
    'Phantom memeace',
    'That one wheel trying to make the kart run over something be like \n\nTHIS IS WHERE THE FUN BEGINS',
    'Re?',
    'r/comedyheaven',
    'removed' ,
   'Dank.(https://youtu.be/b1d7Llx4rm8)',
    'How is there fire underwater',
    'I have to change passwords at my workplace every 3 month. Do you know how annoying it is when it tells you:  \nYour password can\'t match one of your 5 previous passwords.  \nTOO MANY OF THEM',
    'why does this remind me of the indian-made memes i used to see on google+',
    'It\'s not, I tried to log on your account, title is a click bait lie',
    'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'r/ComedyCemetery',
    'Me trying to login to Snapchat to text my friends who my only contact with them is through Snapchat',
    'This happened to me today',
    'nice',
    'But is more stressing wen you forget the password and you decide to send a verification to you email address, *but you don’t remember your email address password either.*',
    'Dude, that\'s LITERALLY my password!',
    'Can we add 46 because its for sex',
    'I RELATE TO THIS ON EVERY LEVEL',
    'Mine is 177013',
    '“Your password was changed 11 months ago”',
    'Happens every time',
    'Copy the one you attempted and paste it and if it doesn\'t work just reset it twice. Big brain password solving.',
    '2011 fb memw',
    'Bruh capitalise that 6' ,
   'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'Nice meme format, sause?',
    'Tip: you can put the meat in a ziplock bag, plug the sink and turn the water to the hottest setting. Takes just a few minutes to defrost.\n\nOr use the microwave defrost setting.\n\n\nThis is just for the people that actually get fucked for not doing it',
    'Nice new format',
    'Thats what chaos mode on microwave is for',
    'My mom walked in the front door right when i read this, and I panicked for some reason lol',
    'This is so wholesome imagine coming from a home with a mother that makes dinner.',
    'Could I get that format please?',
    'Le format pls',
    '#FUCKFUCKFUCKFUCK',
    'Been there, Survived that',
    'This format is godlike, I want it',
    'Me realizing that I haven\'t pulles out of the chicken',
    'r/whenitgoesin',
    'So true',
    'Quick trick: put it in a bag and in any recipient with hot water...',
    'Gots to get out da hair dryer',
    'This happened to me last week also good meme',
    'CHAOS DEFROST!!',
    'Relatable',
    'In an Asian household it tends to be not pressing cook on the rice cooker and u finding out when ur mum comes through the door at that moment',
    'Shove it in the micro wave quick!',
    'Please forgive me Jesus for my dirty brain but I want to ask a question',
    'I just get a hair dryer and light that bitch up',
    'Best movie ever\n\n&amp;#x200B;\n\nMy literal fav' ,
   'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'Pure straightness',
    'Dr. Cosmo Kramer(https://youtu.be/o2X_XNdmWws)',
    'r/comedyhomicide',
    'Mimigrtio',
    'Halifax?',
    'Man ass',
    'Billy Gunn',
    'No',
    'The legend never dies(https://youtu.be/oLoehwYshPc)',
    '*And I am breast man*',
    'We are being overrun in the midfield',
    'i’m the ass man',
    'M Imigrtio',
    'Anyone else think of Rifftrax?',
    'It\'s still quite funny if you. "Say no to ass, man"\n\n(How I originally read it lol)',
    'Mimigratio',
    'No, Ass Man, no.',
    'We want sex man for mayor, not ass man',
    'Mimigrtio: I... Am... Hard to read.',
    'ASS M A N',
    '*clears throat* Sir, I think you meant ass  m a n',
    'say no to mimigrtio',
    '“And I, am RonMan”',
    'Hi inevitable, I’m dad',
    'NO ASS MAN!',
    'Ya like man ass Carson, yeah.',
    'Nice�',
    'Read it as “say no to ass, man”',
    'Kramer busts through the door',
    'I’m stuff',
    'I believe it’s Man ass *-jschlatt*',
    'removed',
    'R/MildlyVandalized',
    'MImigertio',
    'this is the first meme in ages that have actually made me laugh. Thanks',
    'There is one where I live',
    'I mean Mexicans are pretty thicc',
    'Millenials: What the fuck is that even supposed to mean?' ,
   'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us up(https://www.reddit.com/message/compose?to=/r/dankmemes) ^if ^you ^have ^any ^questions. \n\n^( ^I\'m ^a ^bot)',
    'I dont know if this allowed but this is the link \nhttps://www.pornhub.com/view_video.php?viewkey=ph5d08bde25f0e6#4',
    'WHATS HER USERNAME',
    'Give me the name of this porn video',
    'I see your a man of smg4 as well',
    'Source for mario?',
    'Nice',
    'r/gonewild',
    'Sauce?',
    'r/GabbieCarter',
    'Nice',
    'Lol she already made an AMA due to this post.',
    'Unzips...',
    'A lot',
    'Who is she?',
    'that\'s the kind of woman the world needs',
    'u/imawful69 thats her, thank me later' ,
   'Dank.(https://youtu.be/b1d7Llx4rm8)',
    'AtTiTuDe',
    '"THE FUCK\'D YOU SAY TO ME YOU LITTLE SHIT!?"',
    'Parents: Now this is an avengers level threat',
    'I can hear this picture',
    'What the fuck did you just fucking say about me, you little bitch? I\'ll have you know I graduated top of my class in the Navy Seals, and I\'ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I\'m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You\'re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that\'s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn\'t, you didn\'t, and now you\'re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You\'re fucking dead, kiddo.',
    'SHUT UP WHEN IM TALKING TO YOU',
    'YOU KISS YOUR MOTHER WITH THAT MOUTH?!?',
    'If this is a dank meme, **Upvote** this comment!\n\n\nIf this is not a dank meme, **Downvote** this comment!\n\n\nIf this post breaks the rules, **report** it and **Downvote** this comment!\n\n^Thank ^you ^for ^helping ^us ^in ^keeping ^/r/dankmemes ^dank. \n^Hit ^us',
    'r/imagesyoucanhear',
    'Is that fortnite ninja?',
    'AHIAHIAHIJAIHAIHAIHAI SHUT YOUR MOUTH WHEN IM TALKING TO YOU',
    'YOU SHUT YOUR MOUTH WHEN I’M TALKING TO YOU',
    'Honestly, its like I can\'t even be annoyed',
    'DON\'T you swear at me, you little shit! Don\'t you EVER raise your voice at me! I am your mother! You understand? All I do is worry and slave and defend you, and all I get back is that fucking face on your face! So full of disdain and resentment and always so annoyed! Well, now your sister is dead! And I know you miss her and I know it was an accident and I know you\'re in pain and I wish could take that away for you. I WISH I could shield you from the knowledge that you did what you did, but you\'re sister is dead! She\'s gone forever! And what a waste... if it could\'ve maybe brought us together, or something, if you could\'ve just said "I\'m sorry" or faced up to what happened, maybe then we could do something with this, but you can\'t take responsibility for anything! So, now I can\'t accept. And I can\'t forgive. Because... because NOBODY admits anything they\'ve done!',
    'yeah..., i can relate to this...',
    'yOu bEtTeR sToP iT wItH tHoSe cRoCoDiLe tEaRs!!111!!',
    'Thank God other people understand',
    'Bro you need to share with us?',
    'WaTcH YoUR TOnE MIsTeR',
    'Hey dad I’m going to the movies \n\nNibba you want to get that bass out your voice when you talk to me \n\n^^im ^^going ^^to ^^the ^^movies ^^dad ^^hope ^^you ^^don’t ^^mind',
    '"HUHUHUHUHUHUHUUHHUHU SHUT THE FUCK UP WHEN I\'M TALKING TO YOU"',
    'Yeah my parents get really thicc when I get angry as well',
    'i DonT ApREcIaTe yOU TalKinG BacK',
    'fuck you kid youre adopted',
    'Pictures you can hear',
    'Every time',
    'Ninja speak dog...',
    'Frustration is okay... just don\'t whine at me you little shit.',
    '###*Yatamazi!*',
    'F',
    'Why is my screen vibrating'
]

module.exports = {attemptData, metaCanadaData, goingToHellData}
